version: '3'

tasks:
  test:
    - task: build
  clean: rm -rf build/
  # TODO: use caddy version from go.mod
  build:
    deps: [ clean ]
    cmds:
      - ../tools/bin/xcaddy build --output build/caddy --with github.com/jaedle/caddy-s3-proxy=../
