version: '3'

tasks:
  test:
    - task: build
  install-xcaddy: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
  clean: rm -rf build/
  build:
    deps: [ clean ]
    cmds:
      - ../tools/bin/xcaddy build --output build/caddy
