version: '3'

tasks:
  world:
    desc: perform verification + build steps
    aliases: [ default ]
    cmds:
      - task: fmt
      - task: lint
      - task: test

  fmt: go fmt ./...
  lint: golangci-lint run ./...
  test: go test ./...

