version: '3'

tasks:
  install:
    cmd: 'export GOBIN="$PWD/bin" && go install github.com/caddyserver/xcaddy/cmd/xcaddy@${XCADDY_VERSION}'
    env:
      XCADDY_VERSION:
        sh: grep -o 'github.com/caddyserver/xcaddy.*$' go.mod | cut -d ' ' -f2
